name: flutter_create_vscode
description: Um projeto de um app para listar filmes.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_rating_bar: ^4.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/img_claquete.png

fonts:
  - family: Poppins
    fonts:
     - asset: assets/fonts/Poppins/Poppins-Regular.ttf


 
 
     

